<a href="https://colab.research.google.com/github/umidyor/Tensorflow_basics_for_beginners/blob/main/Tensorflow_introduction(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction

In [70]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [7]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [9]:
x=tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [14]:
x=tf.ones((3,3))
x=tf.zeros((2,3))
x=tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


<h1 style="color:red";>Random</h1>

In [24]:
x=tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[ 1.5142109   0.8004993   1.3716071 ]
 [-0.6619044   0.44069314  1.3925068 ]
 [-0.24834241  0.02391396  0.9741589 ]], shape=(3, 3), dtype=float32)


In [27]:
x=tf.random.uniform((3,3),minval=0,maxval=1)
print(x)

tf.Tensor(
[[0.7911252  0.7259625  0.40826142]
 [0.33233964 0.91747415 0.23455536]
 [0.45542598 0.56490564 0.16157424]], shape=(3, 3), dtype=float32)


In [31]:
x=tf.range(start=1,limit=10,delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [32]:
x=tf.cast(x,dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


#Mathematical

In [34]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
z=tf.add(x,y)
z=x+y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [35]:
tf.subtract(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [37]:
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [40]:
print(tf.multiply(x,y))

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [46]:
x=tf.constant([1,2,5])
y=tf.constant([9,8,7])
z=tf.tensordot(x,y,axes=0)
print(z)

tf.Tensor(
[[ 9  8  7]
 [18 16 14]
 [45 40 35]], shape=(3, 3), dtype=int32)


In [47]:
x=tf.constant([1,2,5])
y=tf.constant([9,8,7])
z=tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor(60, shape=(), dtype=int32)


In [48]:
z=tf.reduce_sum(x*y,axis=0)

print(z)

tf.Tensor(60, shape=(), dtype=int32)


In [49]:
z=x**5
print(z)

tf.Tensor([   1   32 3125], shape=(3,), dtype=int32)


In [54]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
# z=x@y
print(z)

tf.Tensor(
[[ 2.3707151   0.50702226 -0.87059045 -0.32526934]
 [-0.58092403  2.3883936   0.6312712  -2.938791  ]], shape=(2, 4), dtype=float32)


#Indexing

In [61]:
x=tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:-1])
print(x[::2])
print(x[:-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1 2 3 1 2], shape=(6,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([0 1 1 2 3 1 2], shape=(7,), dtype=int32)


In [62]:
indices=tf.constant([0,3])
x_ind=tf.gather(x,indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


#Reshaping

In [65]:
x=tf.range(9)
print(x)
x=tf.reshape(x,shape=(3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [69]:
x=tf.transpose(x)
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
